# Generated by Django 3.1.7 on 2022-01-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16)),
                ('hiringDate', models.DateField()),
                ('profileImage', models.ImageField(upload_to='')),
                ('birthdate', models.DateField()),
                ('mobileNo', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
            ],
        ),
    ]
