# Generated by Django 3.1.7 on 2022-01-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialVacations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=16)),
            ],
        ),
    ]
