# Generated by Django 3.1.7 on 2022-01-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0003_auto_20220101_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacationRequests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vFrom', models.DateField()),
                ('vTo', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('numOfDays', models.IntegerField()),
                ('type', models.CharField(choices=[('annualVacation,', 'Annual Vacation,'), ('suddenVacation', 'Sudden Vacation')], default='annualVacation', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('disapprove', 'Disapprove')], default='draft', max_length=15)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RestApi.employee')),
            ],
        ),
    ]
