# Generated by Django 3.1.7 on 2022-01-02 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0004_vacationrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='jobtitle',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='vacationrequests',
            name='type',
            field=models.CharField(choices=[('annualVacation,', 'Annual Vacation,'), ('suddenVacation', 'Sudden Vacation')], max_length=15),
        ),
    ]
