# Generated by Django 3.1.7 on 2022-01-02 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestApi', '0005_auto_20220102_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profileImage',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
